  #VAULT ----------------------------------------------------------------------------------------------
version: '1.0'
services:
  redis-app:
    container_name: redis
    build:
      context: .
    ports:
      - "8099:8099"
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_HOST=$${redis.host}
      - REDIS_PORT=$${redis.port}
      - REDIS_USERNAME=$${redis.username}
      - REDIS_PASSWORD=$${redis.password}